Working branch
410AngelaVu/Responsive-Design pull request #1
Opened 2020-09-11 21:17 UTC by NataJenkins

2020-09-12 02:10 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Great job so far guys :clap: :100: :+1:, your clone looks in too many ways like the original, but you still need to work :hammer: :wrench: :toolbox: more on it, in order to get it approved :checkered_flag:

- [x] below the hero section your articles should take the same width:

|*Clone*|*Original*|
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92984134-f5db7880-f49f-11ea-9001-0f01a11a3978.png) | ![image](https://user-images.githubusercontent.com/34653764/92984144-0390fe00-f4a0-11ea-9266-64f94fc07639.png) |

- [ ] You are messing the latest funding section:

![image](https://user-images.githubusercontent.com/34653764/92984161-21f6f980-f4a0-11ea-879d-38f24835cfa2.png)

- [x] remove the borders from the latest deals articles, the borders are not necessary:
![image](https://user-images.githubusercontent.com/34653764/92984207-67b3c200-f4a0-11ea-8641-b44774c14f62.png)

- [x] you are having a burger menu on desktop view please remove it, and show it only on mobile view as in the original:
![image](https://user-images.githubusercontent.com/34653764/92984273-fb858e00-f4a0-11ea-9988-681b61f71a09.png)

- [ ] we are still on desktop view and your layout changes please fix your media queries to match only tablet and desktop views pixels

|*layout*|
|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92984310-31c30d80-f4a1-11ea-8673-0639f1a5d45f.png) |
| ![image](https://user-images.githubusercontent.com/34653764/92984340-5b7c3480-f4a1-11ea-99bf-2a45b2d95463.png) |

- [ ] CSS styles should use [media queries](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) for 2 breakpoints ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/breakpoints_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/))

* No small break point as it is mobile first and the base styles are for the mobile screen. ([Screenshot on mobile first approach](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/mobile_first.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/))
* medium: min-width around 768px
* large: min-width 1024px

- [ ] Fix the typography here on tablet view:
![image](https://user-images.githubusercontent.com/34653764/92984372-941c0e00-f4a1-11ea-91b9-de0f2e01517d.png)

- [x] Fix the big image on the latest deals section on tablet view and also use some margin to separate your articles, also we should have three articles on a row, not four:
![image](https://user-images.githubusercontent.com/34653764/92984402-c6c60680-f4a1-11ea-9aee-0ffc6045bb93.png)

- [ ] Please fix the header it should match the original:

|*Clone*|*Original*|
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92984454-16a4cd80-f4a2-11ea-9309-77341f0290ef.png) | ![image](https://user-images.githubusercontent.com/34653764/92984451-0f7dbf80-f4a2-11ea-9e88-fe8c5aab87cd.png) |

- [ ] This section should have two articles on a row, not 3, on tablet view of course:

|*Clone*|*Original*|
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92984479-54a1f180-f4a2-11ea-9d45-a3a44fa4be85.png) | ![image](https://user-images.githubusercontent.com/34653764/92984503-726f5680-f4a2-11ea-9285-e3b95111f6fb.png) |

- [ ] you need to put some work on the footer in mobile view:

|*Clone*|*Original*|
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92984519-903cbb80-f4a2-11ea-8ede-c4d6018d0394.png) | ![image](https://user-images.githubusercontent.com/34653764/92984526-a0ed3180-f4a2-11ea-883d-208e6f120974.png) |

- [ ] Fix all the warning and error in the HTML validator, you can fix this by adding a heading to the article tag and use display: none;
![image](https://user-images.githubusercontent.com/34653764/92984574-004b4180-f4a3-11ea-8f6e-68372b0beb2a.png)

- [ ] put your images on the assets/images folder instead of the root directory:
![image](https://user-images.githubusercontent.com/34653764/92984706-fece4900-f4a3-11ea-8b10-5bed2c04e31e.png)

- [ ] divide your HTML page into a header, main and footer section using these semantic tags.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_If you are stuck or have any questions don't hesitate to contact me on slack **@Zakariae El Mejdki**_

2020-09-12 02:10 UTC, elmejdki commented on README.md
> +👤 **Author1**
use your full names here

2020-09-12 02:10 UTC, elmejdki commented on README.md
> +👤 **Author2**
use your full names here

2020-09-12 02:10 UTC, elmejdki commented on style.css
> +  color: red !important;
remove all !important keywords they are not allowed

2020-09-12 02:10 UTC, elmejdki commented on style.css
> +  color: white !important;
remove all !important keywords they are not allowed

2020-09-14 20:33 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

Hey :+1: 

You did a great job here, and the project is almost finished. Generally, you still need to improve the layout of the tablet screen size. Kindly check the inline comments for more details.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-09-14 20:33 UTC, expjazz commented on index.html
> +                    <span class="old as-center">$1200</span>
- [ ] The layout in the tablet view needs to be 3 articles per columns.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/93134391-1decf680-f6af-11ea-8690-2508ab7c7ab6.png) | ![image](https://user-images.githubusercontent.com/61479648/93134473-38bf6b00-f6af-11ea-92ad-1fc53e20bf9d.png) |

2020-09-14 20:33 UTC, expjazz commented on index.html
> +            <p>EverCompliant</p>
- [ ] This needs to be centralized (and occupy more space) on the tablet screen size.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/93134662-702e1780-f6af-11ea-8cc0-aadfd9bdf213.png)|![image](https://user-images.githubusercontent.com/61479648/93134711-820fba80-f6af-11ea-84b6-7e02fd656882.png)  |

2020-09-14 20:33 UTC, expjazz commented on index.html
> +          <p class="main-little">David Canellis4 hours ago</p>
- [ ] The height in the tablet screen size should be a little smaller.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/93134880-c8651980-f6af-11ea-9e41-55349553a2fc.png)| ![image](https://user-images.githubusercontent.com/61479648/93134920-db77e980-f6af-11ea-936f-1119a50bcdec.png) |

2020-09-14 23:58 UTC, arslanbisharat approved these changes
### Congratulations APPROVED :clap:
Hello Team! I can see you worked really hard on this project. I reviewed your [project](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/)  and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 
**Happy Coding**:smiley:
-------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) @slack: arslanbisharat

2020-11-30 14:17 UTC, merged